### PR TITLE
Update the build flow to ToolsVersion 15.0 and Platform toolset v141

### PR DESCRIPTION
**Pull request by oleg-nenashev**
I have some fun with WDK/DDK on my local machine, but maybe it works on reference AppVeyor images

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It seems that it is not going to fly until proper nddll.lib is passed to the build. So far I can pass the 8.1 only, but it won't produce the compatible result I'd guess

**Comment by segrey** [comment]
Shouldn't ntdll be loaded with ```GetModuleHandle(L"ntdll.dll")``` to handle its absence?

**Comment by segrey** [comment]
@oleg-nenashev BTW, what do you think about having possibility in winp to fetch current directory of a process (code like https://github.com/segrey/winpty/commit/a4a6ca3d78b360e3b310f54899d2dfdd5d64981a).

**Comment by oleg-nenashev** [comment]
I managed to get a '140' version on my laptop.

**Comment by oleg-nenashev** [comment]
YAGNI, it was fixed by https://github.com/kohsuke/winp/commit/c6cab68529dd66d4a1ddc037cf0d030c2fdc9e55 for now.

We might end up dropping the WinXP support in the future when there is no compatibility layer offered by Microsoft for newer MVS versions.

**Pull request closed without merging**
